### ISSUE TITLE
"No table found in VOTABLE file" for Simbad MAIN_ID

### ISSUE THREAD

**Issue by Roman-UCLU** [astropy/astroquery#1232]
I spent quite a while trying to figure this out; all in vain. Below is the code of the simplest possible Simbad query:

```Python
from astroquery.simbad import Simbad
result_table = Simbad.query_object("QSO B0003-066")
print(result_table)
```

Here "QSO B0003-066" is, actually, the main Simbad ID of the object ([online](http://simbad.u-strasbg.fr/simbad/sim-basic?Ident=QSO+B0003-066&submit=SIMBAD+search)). The result is the error in the issue title.

Surprisingly, when querying any of the alternative IDs (e.g. "AT20G J000613-062334"), the query works just fine.

Is there something obvious I'm missing?

Thanks!

**Comment by bsipocz** [comment]
What version of astroquery do you use? It works for me as expected:

```
In [88]: from astroquery.simbad import Simbad
    ...: result_table = Simbad.query_object("QSO B0003-066")
    ...: print(result_table)
    ...: 
    ...: 
   MAIN_ID          RA      ... COO_WAVELENGTH     COO_BIBCODE    
                 "h:m:s"    ...                                   
------------- ------------- ... -------------- -------------------
QSO B0003-066 00 06 13.8928 ...              R 2009A&A...493..317L
```

**Comment by Roman-UCLU** [comment]
Thanks, bsipocz.

My version is 0.3.7...

**Comment by bsipocz** [comment]
Weird. There were some recent changes since 0.3.7 in the module, but even with that version the snippet works for me.

Could you check whether the payload and the url is same for you:
```
In [5]: Simbad.query_object("QSO B0003-066", get_query_payload=True)
Out[5]: {'script': '\nvotable {main_id,coordinates}\nvotable open\nquery id  QSO B0003-066  \nvotable close'}

In [6]: Simbad.SIMBAD_URL
Out[6]: 'http://simbad.u-strasbg.fr/simbad/sim-script'
```

also, could you print out `Simbad.last_response.content` and `Simbad.last_table_parse_error` after the query produced the failure?

**Comment by aoberto** [comment]
I assume that it was the same issue than #1232 : a temporary problem in Simbad. It was resolved few hours ago, may be there is some cache ?

**Comment by bsipocz** [comment]
@Roman-UCLU - please try to clear the cache, `Simbad.cache_location` tells you the location.

**Comment by Negar3362** [comment]
Hello, I'm having the same problem with Ned query even after clearing the cache. Using different astropy and astroquery versions, I am still facing the same issue. Are there any solutions to this problem? Thanks.

Here is The code and error:
from astroquery.ipac.ned import Ned
from astroquery import cache_conf

Ned.clear_cache()
result_table = Ned.query_object('NGC 224')

IndexError: No table found in VOTABLE file.

**Comment by keflavich** [comment]
@Negar3362 what versions of astropy & astroquery are you using?  With astropy, astroquery = ('5.1', '0.4.7.dev8846'), I don't see this issue.

**Comment by Negar3362** [comment]
@keflavich The version of Astroquery I'm using is 0.4.6. I'll try 0.4.7 as well. Thanks.
