### ISSUE TITLE
Change in JPL HORIZONS output has broken ephemeris query

### ISSUE THREAD

**Issue by talister** [astropy/astroquery#1619]
With the January 21/Version 4.67 release of the JPL HORIZONS code/service (https://ssd.jpl.nasa.gov/?horizons_news), the output column quantities have changed and no longer match the expected value leading to a `KeyError` crash:
```python
from astroquery.jplhorizons import Horizons
eph = Horizons(id='35107', epochs={'start' : "2020-01-21 00:00", 'stop' : "2020-01-22 00:00", 'step' : '1h'}, location='W86')
ephem = eph.ephemerides(quantities='1,3,4,9,19,20,23,24,38,42')
```

This produces:
```python

~/venv/neoexchange36-venv/lib/python3.6/site-packages/astroquery/jplhorizons/core.py in _parse_horizons(self, src)
   1245         rename = []
   1246         for col in data.columns:
-> 1247             data[col].unit = column_defs[col][1]
   1248             if data[col].name != column_defs[col][0]:
   1249                 rename.append(data[col].name)

KeyError: 'R.A._(ICRF)'
```

The fix is simply to add the new column names in the `eph_columns` dictionary in the  `astroquery/jplhorizons/__init__.py`. I have done this in a local fork of the code if you want me to create a PR: https://github.com/astropy/astroquery/compare/master...talister:master

**Comment by bsipocz** [comment]
@talister - Yes, please, a PR would be very much welcome.

cc @mommermi

**Comment by fraserw** [comment]
Has this correction been pushed forward in the latest pypi version, 0.4? I was unable to recreate it using that version.

**Comment by talister** [comment]
Yes it's in 0.4, see the entry under `jplhorizons` in the `CHANGES.rst`
 @bsipocz am I supposed to close this issue now or is that a Project Thing (Tm) ?

**Comment by bsipocz** [comment]
It's just an oversight. I learnt to rely on the PRs to close the related issues, but didn't pay attention that the magic words were missing when I merged it.

**Comment by mmarsset** [comment]
Hello, I have installed the latest version (0.4) of astroquery and still get some errors for some ephemeris parameters such as ObsSub-LON.

**Comment by bsipocz** [comment]
please reinstall it with `pip install --pre -U astroquery`

**Comment by mmarsset** [comment]
Thank you very much, that worked !
