### ISSUE TITLE
Calculating TESS BJD to HJD Accounting for Light Time Travel

### ISSUE THREAD

**Issue by kjkoeller** [astropy/astroquery#2702]
Using `Atroquery==0.4.6` I am trying to convert the TESS given `BJD_TDB` to HJD for a common time between multiple datasets. I have tried the following code but end with the errors of:

`ValueError: Query failed without known error message; received the following response:
API VERSION: 1.2
API SOURCE: NASA/JPL Horizons API`

and

`No site matches. Use "*@body" to list, "c@body" to enter coords, ?! for help.`

However, using the this link https://ssd.jpl.nasa.gov/horizons.cgi, I found the ID for TESS to be -95, so I am not sure what the issue is and an example `BJD = 2459882.3345982665`.

```python
from astropy.time import Time
from astroquery.jplhorizons import Horizons
from astropy.coordinates import EarthLocation
from astropy.coordinates import EarthLocation, CartesianRepresentation, CartesianDifferential, SkyCoord, GCRS
from astropy import units as u
from astropy.coordinates import SkyCoord
import astropy.coordinates as coord

obs_time_bjd_tdb = Time(bjd, format='jd', scale='tdb')

obs_location = EarthLocation.from_geodetic(-111.6 * u.deg, 31.9 * u.deg, 2097 * u.m)

# Fetch the TESS satellite position at the observation time
tess = Horizons(id='-95', id_type='majorbody', location=obs_location, epochs=obs_time_bjd_tdb)
tess_vectors = tess.vectors()
  
# Extract the TESS satellite position in Cartesian coordinates (in km)
tess_pos = CartesianRepresentation(tess_ephem['x'], tess_ephem['y'], tess_ephem['z'], unit='au')
tess_gcrs = GCRS(tess_pos, obstime=Time(tess_ephem['datetime_jd'], format='jd'),
                             representation_type='cartesian')
  
# Convert from BJD to HJD
obs_time_hjd = obs_time_bjd_tdb + (
                        tess_gcrs.get_observer_barycentric(obs_time_bjd) - observer_location).get_light_travel_time(
                obs_time_bjd)
```

**Comment by mkelley** [comment]
Hi @kjkoeller , the format for topocentric queries is a dictionary:
```
        location : str or dict, optional
            Observer's location for ephemerides queries or center body name for
            orbital element or vector queries. Uses the same codes as JPL
            Horizons. If no location is provided, Earth's center is used for
            ephemerides queries and the Sun's center for elements and vectors
            queries. Arbitrary topocentric coordinates for ephemerides queries
            can be provided in the format of a dictionary. The dictionary has to
            be of the form {``'lon'``: longitude in deg (East positive, West
            negative), ``'lat'``: latitude in deg (North positive, South
            negative), ``'elevation'``: elevation in km above the reference
            ellipsoid, [``'body'``: Horizons body ID of the central body;
            optional; if this value is not provided it is assumed that this
            location is on Earth]}.
```

That said, using a dictionary instead of the `EarthLocation` object will still fail, because topo-centered queries are blocked by the code.  Maybe it wasn't possible when the vector query was written?  Anyway, it should work now, so I will make fix for this.

**Comment by mkelley** [comment]
Actually, I take some of that back.  The topo queries do work with vectors now.  I was just using an older version where it was blocked (fixed in #2625 ).

**Comment by kjkoeller** [comment]
So in what way would I be fixing the error that I am receiving with the code that I am using?

**Comment by kjkoeller** [comment]
I still receive the same error of:

```
ValueError: Query failed without known error message; received the following response:
API VERSION: 1.2
API SOURCE: NASA/JPL Horizons API

******************************************************************************
 Revised: May 02, 2023              TESS / (Earth)                          -95
                        https://tess.gsfc.nasa.gov/index.html 
                   http://spaceflight101.com/tess/tess-orbit-design/ 

 BACKGROUND:
.
.
.
```
For the following code only changing the location to a dictionary instead.
```python
# Specify the observer location and time of the observation
obs_time_bjd_tdb = Time(bjd, format='jd', scale='tdb')

# Set the observation location on Earth
# Example location of Kitt Peak National Observatory
# obs_location = EarthLocation.from_geodetic(-111.6 * u.deg, 31.9 * u.deg, 2097 * u.m)

obs_location = {
    'lon': -31.9*u.deg,
    'lat': -111.6*u.deg,
    'elevation': 2097*u.m
}

# Fetch the TESS satellite position at the observation time
tess = Horizons(id='-95', id_type='majorbody', location=obs_location, epochs=obs_time_bjd_tdb)
tess_vectors = tess.ephemerides()

# Extract the TESS satellite position in Cartesian coordinates (in km)
tess_pos = CartesianRepresentation(tess_vectors['x'], tess_vectors['y'], tess_vectors['z'], unit='au')
tess_gcrs = GCRS(tess_pos, obstime=Time(tess_ephem['datetime_jd'], format='jd'),
                 representation_type='cartesian')

# Convert from BJD to HJD
obs_time_hjd = obs_time_bjd_tdb + (
            tess_gcrs.get_observer_barycentric(obs_time_bjd) - observer_location).get_light_travel_time(
    obs_time_bjd)
```

I tried for the `tess` variable using `.vectors()` but that causes a different error of:
`ValueError: cannot use topographic position in statevectors query`

I have even tried `ephemerides_async()` (the following error) and `vectors_async()` (same error as above):
`TypeError: 'Response' object is not subscriptable`

**Comment by mkelley** [comment]
The documentation isn't clear that it does not accept astropy Quantities.  We should fix it so that quantities are allowed.  Also, I got the same error with v0.4.6, but it does work with the "pre-release" version, which can be installed via `pip -U --pre astroquery`.  The following code runs for me with the most recent version on pip: v0.4.7.dev8479.

(verify your latitude and longitude before using, also note that `Horizons` needs them as degrees and elevation in km)

```python
from astropy.time import Time
from astroquery.jplhorizons import Horizons
from astropy.coordinates import EarthLocation
from astropy.coordinates import EarthLocation, CartesianRepresentation, CartesianDifferential, SkyCoord, GCRS
from astropy import units as u
from astropy.coordinates import SkyCoord
import astropy.coordinates as coord

bjd = 2459882.3345982665
obs_time_bjd_tdb = Time(bjd, format='jd', scale='tdb')
obs_location = {
    'lon': 111.6,
    'lat': 31.9,
    'elevation': 2.097
}
tess = Horizons(id='-95', id_type='majorbody', location=obs_location, epochs=obs_time_bjd_tdb)
tess_vectors = tess.vectors()
```

```
<Table masked=True length=1>
       targetname          datetime_jd    ...         range               range_rate     
          ---                   d         ...           AU                  AU / d       
         str23               float64      ...        float64               float64       
----------------------- ----------------- ... --------------------- ---------------------
TESS (spacecraft) (-95) 2459882.334598267 ... 0.0008642069900366986 8.049245701909611e-05
```

**Comment by kjkoeller** [comment]
Thank you so much, that now works, however the end goal is to receive the light time travel to a location on the earth from the TESS satellite. When I use this code after the code you provided I receive error following the code:

```python
# Extract the TESS satellite position in Cartesian coordinates (in km)
tess_pos = CartesianRepresentation(tess_vectors['x'], tess_vectors['y'], tess_vectors['z'], unit='au')
tess_gcrs = GCRS(tess_pos, obstime=Time(tess_vectors['datetime_jd'], format='jd'),
                 representation_type='cartesian')

# Convert from BJD to HJD
obs_time_hjd = obs_time_bjd_tdb + (
            tess_gcrs.get_observer_barycentric(obs_time_bjd) - observer_location).get_light_travel_time(
    obs_time_bjd)
```

```
WARNING: AstropyDeprecationWarning: ``id_type``s 'majorbody' and 'id' are deprecated and replaced with ``None``, which has the same functionality. [astroquery.jplhorizons.core]
Traceback (most recent call last):
  File "C:\Users\Kyle\OneDrive\PhysicsAstro\Astronomy\Code\Tess_Search\tesscut.py", line 191, in <module>
    main("tess-s0059-3-1_7.116535_78.961849_88x88_astrocut.fits", "C:\\New folder")
  File "C:\Users\Kyle\OneDrive\PhysicsAstro\Astronomy\Code\Tess_Search\tesscut.py", line 142, in main
    tess_gcrs.get_observer_barycentric(obs_time_bjd) - observer_location).get_light_travel_time(
  File "C:\Users\Kyle\AppData\Local\Programs\Python\Python39\lib\site-packages\astropy\coordinates\baseframe.py", line 1765, in __getattr__
    return self.__getattribute__(attr)  # Raise AttributeError.
AttributeError: 'GCRS' object has no attribute 'get_observer_barycentric'
```

**Comment by kjkoeller** [comment]
I ended up using the following code instead and the difference between `BJD_TDB` and the `HJD` counterpart is only 1.1 minutes off.

```python
def bary_to_helio(ra, dec, bjd, obs_name):
    bary = Time(bjd, scale='tdb', format='jd')
    obs = EarthLocation.of_site(obs_name)
    star = SkyCoord(ra, dec, unit=(u.hour, u.deg))
    ltt = bary.light_travel_time(star, 'barycentric', location=obs)
    guess = bary - ltt
    delta = (guess + guess.light_travel_time(star, 'barycentric', obs)).jd - bary.jd
    guess -= delta * u.d

    ltt = guess.light_travel_time(star, 'heliocentric', obs)
    return guess.utc + ltt
```

**Comment by bsipocz** [comment]
@kjkoeller - Where do you see an existing `get_observer_barycentric` method? I only see a `get_body_barycentric` function, but not a single class method, etc.

So, this very much looks like something not related to astroquery anymore, so I would go ahead and close this issue as we can't really do much about it here. For more "how to do XYZ" related questions, I would suggest raising them on the openastronomy discourse forum: https://community.openastronomy.org/

**Comment by kjkoeller** [comment]
Yes I think you are right and I may have some packages mixed up. This can be closed now, thank you so much for the help!
