### ISSUE TITLE
Simbad queries

### ISSUE THREAD

**Issue by pavolgaj** [astropy/astroquery#3150]
I have started to have some problems using astroquery with Simbad. I use the dev version 0.4.8. When I run the query (e.g. Simbad.query_object('tet01 Ori C')), I got error:

> Traceback (most recent call last):
  File "<pyshell#15>", line 1, in <module>
    theta1c = Simbad.query_object('tet01 Ori C')
  File "/usr/local/lib/python3.12/dist-packages/astropy/utils/decorators.py", line 603, in wrapper
    return function(*args, **kwargs)
  File "/usr/local/lib/python3.12/dist-packages/astroquery/simbad/core.py", line 598, in query_object
    return self._query(top, columns, joins, instance_criteria,
  File "/usr/local/lib/python3.12/dist-packages/astroquery/simbad/core.py", line 1431, in _query
    maxrec=self.hardlimit,
  File "/usr/local/lib/python3.12/dist-packages/astroquery/simbad/core.py", line 165, in hardlimit
    self._hardlimit = self.tap.hardlimit
  File "/usr/local/lib/python3.12/dist-packages/pyvo/dal/tap.py", line 236, in hardlimit
    return self.get_tap_capability().outputlimit.hard.content
  File "/usr/local/lib/python3.12/dist-packages/pyvo/dal/tap.py", line 138, in get_tap_capability
    for capa in self.capabilities:
  File "/usr/local/lib/python3.12/dist-packages/astropy/utils/decorators.py", line 836, in __get__
    val = self.fget(obj)
  File "/usr/local/lib/python3.12/dist-packages/pyvo/dal/vosi.py", line 98, in capabilities
    return vosi.parse_capabilities(self._capabilities().read)
  File "/usr/local/lib/python3.12/dist-packages/pyvo/io/vosi/endpoint.py", line 137, in parse_capabilities
    config=config, pos=(1, 1)).parse(iterator, config)
  File "/usr/local/lib/python3.12/dist-packages/pyvo/io/vosi/endpoint.py", line 346, in parse
    vo_raise(E10, config=config, pos=pos)
  File "/usr/local/lib/python3.12/dist-packages/astropy/io/votable/exceptions.py", line 124, in vo_raise
    raise exception_class(args, config, pos)
pyvo.io.vosi.exceptions.E10: None:12:0: E10: File does not appear to be a VOSICapabilities file

A few days before, it worked fine. Also, the stable version of astroquery 0.4.7 looks to work.

**Comment by keflavich** [comment]
I can reproduce this issue.

**Comment by aoberto** [comment]
Hello,
Sorry about this issue, the server restarted with a bad configuration during the weekend. It is fixed now.

**Comment by keflavich** [comment]
Thanks @aoberto !  Glad to hear it was fixed.

**Comment by pavolgaj** [comment]
I just tested it. Unfortunately, it still doesn't work for me...

**Comment by aoberto** [comment]
it just take few minutes to be released ...

**Comment by pavolgaj** [comment]
Thanks. It works now :D
